version: '3.8'
services:
  stereowood:
    image: ${DOCKER_IMAGE:-stereowood-color-system:latest}
    container_name: stereowood-color-system
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PORT=9099
      - NODE_ENV=production
      - DB_FILE=/data/database.db
    ports:
      - "${HOST_PORT:-9099}:${PORT:-9099}"
    volumes:
      - stereowood-data:/data
      - stereowood-uploads:/app/uploads
      - stereowood-backups:/app/backups
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://127.0.0.1:${PORT:-9099}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - stereowood-network

networks:
  stereowood-network:
    driver: bridge

volumes:
  stereowood-data:
    name: stereowood-data
  stereowood-uploads:
    name: stereowood-uploads
  stereowood-backups:
    name: stereowood-backups
